### ISSUE TITLE
"Missing value for cloud"

### ISSUE THREAD

**Issue by bulebuk** [humanendpoint/confluence-sync#1]
It looks like the Python script is looking for an environment variable named `cloud` but it is set as `INPUT_CLOUD` by the action? Similar issue for the other settings.

https://github.com/humanendpoint/confluence-syncer/blob/main/bin/main.py#L25

```yaml
      uses: humanendpoint/confluence-syncer@v1.6
      with:
          input_md_directory: markdown_output
          cloud: redacted
          space_id: redacted
          parent_page_id: redacted 
          user: ${{ secrets.ATLASSIAN_USERNAME }}
          token: ${{ secrets.ATLASSIAN_API_TOKEN }}
 ```

```
/usr/bin/docker run --name redcated --label redcated --workdir /github/workspace --rm -e "pythonLocation" -e "PKG_CONFIG_PATH" -e "Python_ROOT_DIR" -e "Python2_ROOT_DIR" -e "Python3_ROOT_DIR" -e "LD_LIBRARY_PATH" -e "INPUT_INPUT_MD_DIRECTORY" -e "INPUT_CLOUD" -e "INPUT_SPACE_ID" -e "INPUT_PARENT_PAGE_ID" -e "INPUT_USER" -e "INPUT_TOKEN" -e "INPUT_INPUT_FILE" -e "INPUT_EXCLUDE_FILES" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFL
Missing value for cloud
```

Cool project btw.
